# frozen_string_literal: true

source "https://rubygems.org"

gem "websocket-client-simple"
gem "colorize"
gem "faraday"
gem "rspec"
gem "dotenv"
gem "byebug"
gem "activerecord"
gem "sqlite3"
gem "rake"
